# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 08:08
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inserts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название рекламной вставки')),
                ('url', models.URLField(verbose_name='URL потока')),
                ('time', models.TimeField(verbose_name='Время начала')),
                ('volume', models.PositiveSmallIntegerField(default=50, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Громкость')),
            ],
            options={
                'verbose_name_plural': 'Рекламные вставки',
                'verbose_name': 'Рекламные вставка',
            },
        ),
        migrations.CreateModel(
            name='MainStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL потока')),
                ('volume', models.PositiveSmallIntegerField(default=50, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Громкость')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Название потока')),
            ],
            options={
                'verbose_name_plural': 'Основные потоки',
                'verbose_name': 'Основной поток',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(help_text='Уникальное значение, не более 10 символов', max_length=10, unique=True, verbose_name='ID плеера')),
                ('title', models.CharField(max_length=255, verbose_name='Описание')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес установки')),
                ('update_granted', models.BooleanField(default=False, verbose_name='Разрешено обновление')),
            ],
            options={
                'verbose_name_plural': 'Плееры',
                'verbose_name': 'Плееры',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(None, 'Нет полученного статуса'), (0, 'ОК'), (1, 'Нет текущего расписания'), (2, 'Главный поток закончился'), (3, 'Ошибка главного плеера'), (4, 'Ошибка рекламного плеера')], default=None, null=True, verbose_name='Статус плеера')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 12, 18, 10, 8, 45, 112591), verbose_name='Статус на')),
                ('current_sch_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего расписания')),
                ('describe', models.TextField(blank=True, verbose_name='Описание состояние')),
                ('player_version', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Версия плеера')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='Orpheus.Player', verbose_name='Плеер')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название расписания')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('inserts', models.ManyToManyField(blank=True, related_name='inserts', to='Orpheus.Inserts', verbose_name='Рекламные вставки')),
                ('main_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_stream', to='Orpheus.MainStream', verbose_name='Главный поток')),
            ],
            options={
                'verbose_name_plural': 'Расписания',
                'verbose_name': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Silent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('time_start', models.TimeField(verbose_name='Начало тихой зоны')),
                ('time_end', models.TimeField(verbose_name='Конец тихой зоны')),
            ],
            options={
                'verbose_name_plural': 'Зоны тишины',
                'verbose_name': 'Зона тишины',
            },
        ),
        migrations.CreateModel(
            name='UpdateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
                ('url', models.FileField(upload_to='updater', verbose_name='URL файла')),
            ],
            options={
                'verbose_name_plural': 'Update скрипты',
                'verbose_name': 'Update скрипт',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='silent',
            field=models.ManyToManyField(blank=True, related_name='silent', to='Orpheus.Silent', verbose_name='Зоны тишины'),
        ),
        migrations.AddField(
            model_name='player',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orpheus.Schedule', verbose_name='Расписание'),
        ),
    ]
