# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 10:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inserts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('url', models.URLField(verbose_name='URL потока')),
                ('time', models.TimeField(verbose_name='Время начала')),
                ('volume', models.PositiveSmallIntegerField(default=50, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Громкость')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('address', models.CharField(default='None', max_length=100, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='MainStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL потока')),
                ('volume', models.PositiveSmallIntegerField(default=50, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Громкость')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserts', models.ManyToManyField(blank=True, null=True, related_name='inserts', to='Orpheus.Inserts')),
                ('main_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_stream', to='Orpheus.MainStream')),
            ],
        ),
        migrations.CreateModel(
            name='Silent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('time_start', models.TimeField(verbose_name='Начало тихой зоны')),
                ('time_end', models.TimeField(verbose_name='Конец тихой зоны')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='silent',
            field=models.ManyToManyField(blank=True, null=True, related_name='silent', to='Orpheus.Silent'),
        ),
        migrations.AddField(
            model_name='location',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orpheus.Schedule'),
        ),
    ]
