# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orpheus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inserts',
            options={'verbose_name': 'Вставка', 'verbose_name_plural': 'Вставки'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация (e.g. магазин)', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='mainstream',
            options={'verbose_name': 'Основной поток', 'verbose_name_plural': 'Основные потоки'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='silent',
            options={'verbose_name': 'Зона тишины', 'verbose_name_plural': 'Зоны тишины'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='change_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(default='spec', max_length=255, verbose_name='Название расписания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='inserts',
            field=models.ManyToManyField(blank=True, related_name='inserts', to='Orpheus.Inserts'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='silent',
            field=models.ManyToManyField(blank=True, related_name='silent', to='Orpheus.Silent'),
        ),
    ]
