# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orpheus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatefile',
            options={'get_latest_by': 'version', 'verbose_name': 'Update скрипт', 'verbose_name_plural': 'Update скрипты'},
        ),
        migrations.AddField(
            model_name='player',
            name='send_updater',
            field=models.BooleanField(default=False, verbose_name='Отправить АПДЕЙТЕР'),
        ),
        migrations.AddField(
            model_name='playerstatus',
            name='updater_present',
            field=models.BooleanField(default=False, verbose_name='Аапдейтер в наличии'),
        ),
        migrations.AddField(
            model_name='updatefile',
            name='file_type',
            field=models.CharField(choices=[('updater.py', 'UPDATER'), ('api_player.py', 'PLAYER')], default=None, max_length=20, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='player',
            name='update_granted',
            field=models.BooleanField(default=False, verbose_name='Разрешено обновление ПЛЕЕРА'),
        ),
        migrations.AlterField(
            model_name='playerstatus',
            name='describe',
            field=models.TextField(blank=True, verbose_name='Описание состояния'),
        ),
        migrations.AlterField(
            model_name='playerstatus',
            name='player_version',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Версия плеера'),
        ),
        migrations.AlterField(
            model_name='playerstatus',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 16, 4, 30, 679478), verbose_name='Статус на'),
        ),
    ]
