# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orpheus', '0002_auto_20171218_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstatus',
            options={'verbose_name': 'Статус плеера', 'verbose_name_plural': 'Статус плеера'},
        ),
        migrations.RemoveField(
            model_name='playerstatus',
            name='describe',
        ),
        migrations.AlterField(
            model_name='playerstatus',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 22, 36, 27, 967396), verbose_name='Статус на'),
        ),
        migrations.AlterField(
            model_name='playerstatus',
            name='updater_present',
            field=models.BooleanField(default=False, verbose_name='Апдейтер в наличии'),
        ),
    ]
