# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orpheus', '0002_auto_20171103_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inserts',
            options={'verbose_name': 'Рекламные вставка', 'verbose_name_plural': 'Рекламные вставки'},
        ),
        migrations.AlterField(
            model_name='inserts',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название рекламной вставки'),
        ),
        migrations.AlterField(
            model_name='location',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orpheus.Schedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='mainstream',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Название потока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='inserts',
            field=models.ManyToManyField(blank=True, related_name='inserts', to='Orpheus.Inserts', verbose_name='Рекламные вставки'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='main_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_stream', to='Orpheus.MainStream', verbose_name='Главный поток'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='silent',
            field=models.ManyToManyField(blank=True, related_name='silent', to='Orpheus.Silent', verbose_name='Зоны тишины'),
        ),
    ]
