# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orpheus', '0003_auto_20171103_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserts',
            name='url',
            field=models.FilePathField(verbose_name='URL потока'),
        ),
    ]
