# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orpheus', '0003_auto_20171222_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatus',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 23, 19, 41, 58967), verbose_name='Статус на'),
        ),
    ]
