# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orpheus', '0004_auto_20171114_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserts',
            name='url',
            field=models.FileField(upload_to='', verbose_name='URL потока'),
        ),
    ]
