# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orpheus', '0005_auto_20171114_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserts',
            name='url',
            field=models.URLField(verbose_name='URL потока'),
        ),
    ]
