# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orpheus', '0002_auto_20170406_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_stream', models.FilePathField(verbose_name='Путь к основной музыке')),
                ('main_volume', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Громкость основной темы')),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(default='None', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.IntegerField(unique=True, verbose_name='Магазин №'),
        ),

    ]
