# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orpheus', '0003_auto_20170406_1738'),
    ]

    operations = [

        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='main_stream',
            field=models.URLField(verbose_name='Путь к основной музыке'),
        ),
    ]
