# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orpheus', '0004_auto_20170406_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orpheus.Schedule'),
        ),
    ]
