# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orpheus', '0005_shop_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.CharField(default='None', max_length=200, verbose_name='Описание'),
        ),
    ]
