# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orpheus', '0007_auto_20170407_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Описание'),
        ),
    ]
